jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v1
    - continue-on-error: true
      name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - continue-on-error: true
      name: Build with Gradle
      run: ./gradlew build
    - continue-on-error: true
      if: always()
      name: robocode.core test artifacts
      uses: actions/upload-artifact@v2
      with:
        name: robocode.core-test-result
        path: robocode.core/build/reports/tests/test
    - continue-on-error: true
      if: always()
      name: robocode.host test artifacts
      uses: actions/upload-artifact@v2
      with:
        name: robocode.host-test-result
        path: robocode.host/build/reports/tests/test
    - continue-on-error: true
      if: always()
      name: robocode.tests test artifacts
      uses: actions/upload-artifact@v2
      with:
        name: robocode.tests-result
        path: robocode.tests/build/reports/tests/test
    - continue-on-error: true
      name: setup binary artifact
      uses: actions/upload-artifact@v2
      with:
        path: build/robocode-*-setup.jar
name: Java CI
on:
  repository_dispatch:
    types: trigger-ga___assembly.yml
